# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://zzolza.github.io/
title: Fast Landing
email: galichy79@gmail.com
author: Yuriy Galych
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2022. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: telegram
    url: https://t.me/vlad1038063
  - title: viber
    url: #
  - title: skype
    url: https://join.skype.com/invite/JhNL2H4iSc4X
